version: '2'
services:
  db:
    image: hub.c.163.com/library/mysql:5.7
    container_name: zipkin_mysql
    volumes:
      - /Users/Workspaces/libraries/tracing/zipkin-server-with-mysql/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 3306:3306
    networks: 
      - default 
      - zipkin_net
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_server
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_DB=zipkin
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_HOST=zipkin_mysql
      - MYSQL_TCP_PORT=3306
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    networks: 
      - default 
      - zipkin_net
networks: 
  zipkin_net: 
    external: true